### ISSUE TITLE
Corrections aux notes

### ISSUE THREAD

**Issue by flad887** [blondimi/igl752_a20#1]
**Page 4**: Dans l'encadré en bas de page, si on parle bien du système T1 de la page 1, le chemin s1->s2->s1->s2 utilise une transition non définie (s2->s1).
**Page 30**: Dans le premier encadré, on mentionne que 

> la seule manière de lire le premier _a_ [de l'automate B] consiste à se déplacer dans l'état _q_

Cependant, on peut aussi se déplacer dans l'état _r_. Le problème pour le mot _abaaa_... survient plutôt après le _b_.

**Comment by blondimi** [comment]
C'est corrigé, merci!
