### ISSUE TITLE
Suggestions mineures pour les notes (2)

### ISSUE THREAD

**Issue by flad887** [blondimi/igl752_a20#3]
Page 57: deuxième paragraphe

> ce-dernier -> ce dernier

Page 58: deuxième paragraphe

> Une formule CTL est **dite<del>s</del>**

Page 59: deuxième paragraphe de la section 6.2.1

> Ainsi, s0 |= ∃XΦ ssi **s0** possède au moins un successeur

Page 59: premier paragraphe de la section 6.2.2. Je ne suis pas certain de la formulation exprimée mais dans la vidéo [6c](https://youtu.be/seyLjdXtZL0?t=70) on indique que s0 doit d'abord satisfaire Φ. Je ne sais pas à quoi on fait référence pour ce s mais il semble qu'il devrait aussi satisfaire Φ.

> Ainsi, s ∈ T ssi **s |=Φ et** il existe un état s′ ∈ Post(s) [...]

**Comment by blondimi** [comment]
C'est corrigé, merci. Au passage, je t'ai ajouté aux remerciements dans l'avant-propos, svp me faire signe si ce n'est pas OK.
