### ISSUE TITLE
Suggestions mineures pour les notes (3)

### ISSUE THREAD

**Issue by flad887** [blondimi/igl752_a20#4]
Page 83: deuxième paragraphe

> où v **décrit/est** le contenu du reste de la pile

Page 84: deuxième ligne

> mettre l’emphase sur le système <del>dont</del> **auquel** nous faisons référence

Page 84: dernier paragraphe

> Par <del>soucis</del> **souci** technique

Page 85: dernier paragraphe

> <del>Un</del> **Une** telle procédure

Page 88: Figure 8.3 -> Il manque une accolade pour fermer l'ensemble décrit

L'explication pour [l'assertion](https://youtu.be/zPFrRdO1wrE?t=119) est en contradiction avec les notes. Je crois qu'il s'agit d'une erreur d'inattention lors de l'enregistrement et que les notes sont correctes.

**Comment by blondimi** [comment]
Merci! C'est corrigé et j'ai ajouté un commentaire sur YouTube pour expliquer l'erreur.
